(function() {var implementors = {};
implementors["webrender"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"struct\" href=\"webrender/struct.DebugFlags.html\" title=\"struct webrender::DebugFlags\">DebugFlags</a>&gt; for <a class=\"struct\" href=\"webrender/struct.DebugFlags.html\" title=\"struct webrender::DebugFlags\">DebugFlags</a>",synthetic:false,types:["webrender::renderer::DebugFlags"]},];
implementors["webrender_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"struct\" href=\"webrender_api/struct.HitTestFlags.html\" title=\"struct webrender_api::HitTestFlags\">HitTestFlags</a>&gt; for <a class=\"struct\" href=\"webrender_api/struct.HitTestFlags.html\" title=\"struct webrender_api::HitTestFlags\">HitTestFlags</a>",synthetic:false,types:["webrender_api::api::HitTestFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"struct\" href=\"webrender_api/struct.CaptureBits.html\" title=\"struct webrender_api::CaptureBits\">CaptureBits</a>&gt; for <a class=\"struct\" href=\"webrender_api/struct.CaptureBits.html\" title=\"struct webrender_api::CaptureBits\">CaptureBits</a>",synthetic:false,types:["webrender_api::api::CaptureBits"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"struct\" href=\"webrender_api/struct.ClearCache.html\" title=\"struct webrender_api::ClearCache\">ClearCache</a>&gt; for <a class=\"struct\" href=\"webrender_api/struct.ClearCache.html\" title=\"struct webrender_api::ClearCache\">ClearCache</a>",synthetic:false,types:["webrender_api::api::ClearCache"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"struct\" href=\"webrender_api/struct.FontInstanceFlags.html\" title=\"struct webrender_api::FontInstanceFlags\">FontInstanceFlags</a>&gt; for <a class=\"struct\" href=\"webrender_api/struct.FontInstanceFlags.html\" title=\"struct webrender_api::FontInstanceFlags\">FontInstanceFlags</a>",synthetic:false,types:["webrender_api::font::FontInstanceFlags"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
